//QUESTO E' FILE Recipiente.java

//Alla classe diamo il nome del file che abbiamo creato

//PUBLIC = "indica che la classe è pubblica e le altre classi ci possono accedere"
public class Recipiente{
    //ORA DOBBIAMO DEFINIRE COME SONO FATTI GL'OGGETTI DELLA CLASSE, LO STATO DEL RECIPIENTE SARA' IN BASE ALLA QUANTITA'
    //NEL RECIPIENTE DOBBIAMO SAPRE IL VOLUME E IL CONTENUTO E LA CAPIENZA

    //CAMPI O VARIABILI DI DISTANZA CIOE' OGNI RECIPIENTE MI DICE IL VOLUME E IL CONTENUTO

    //PRIVATE = "MODIFICATORE DI ACCESSO CI DICE CHE I CAMPI CHE DEFINITI SONO PRIVATI CIOE' 
    //POSSONO ESSERE UTILIZZATE SOLO DALLA CLASSE Recipiente E  
    // NON E' POSSIBILE ACCEDERCI ALL'INTERO"

    //ALCUNE DELLE COMBINAZIONI SONO PRIVI DI SENSO
    private int volume; //INFATTI IL VOLUME NON PUO' ESSERE UN VALORE NEGATIVO MA PIU' GRANDE DI 0
    private int contenuto; //IL CONTENUTO DEVE ESSERE MAGGIO DI 0  E MINORE O UGUALE AL VOLUME

    // CON DIVERSE OPERAZIONI SI POSSONO LEGGERE I VALORI DELLA CLASSE Recipiente 

    //SE VOGLIO PERMETTERE QUALCHE FORMA DI OPERAZIONE ALL'INTERNO DELLA CLASSE DEVO
    //SVOLGERE DIVERSE OPERAZIONI QUESTO PARADIGMA SI CHIAMA PRINCIPIO D INCAPSULAMENTO

    //L'OPERAZIONE E' QUELLA SOTTOSTANTE SI CREA UN'ISTANZA(COSTRUTTORE) DELLA CLASSE

    public Recipiente (int quantità){ //quantità maggiore di 0
        volume = quantità;
        contenuto = 0;
    }

    //METODO PER CONOSCERE  IL VALORE DI UNA CLASSE CHE POSSIEDE VARIABILI PRIVATE
    //NON SI PUO' CONOSCERE PIU' VARIABILI UTILIZZANDO LO STESSO METODO MA BISOGNA CREARE UN'ALTRA ISTANZA
    public int get_volume() {return volume;}
    public int get_contenuto() {return contenuto;}
    //NON METTIAMO IL GET PERCHE' NON RICHIAMIAMO UNA VARIABILE ESISTENTE MA UTILIZZIAMO 
    public int capacità(){return volume - contenuto;}

    //METODO PER AGGIUNGERE LA QUANTITA' DI LIQUIDO NEL RECIPIENTE
    public void aggiungi(int quantità){
        //AGGIORNIAMO IL CAMPO DEL CONTENUTO AGGIUNGENDO IL LIQUIDO NEL CONTENUTO
        //MATH.MIN PERMETTE DI NON SUPERARE L'ECCESSO DEL RECIPIENTE E CONTROLLA SE LA SOMMA CHE FACCIAMO
        // NON SUPERI IL VOLUME CHE IMPOSTIAMO
         contenuto = Math.min(contenuto + quantità,volume);
    }

    public void rimuovi(int quantità){
        contenuto = contenuto - quantità;
    }

}